import { Dimensions, Platform, StyleSheet } from "react-native";

const { width } = Dimensions.get("window");

const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  scrollContainer: {
    flexGrow: 1,
    paddingHorizontal: 16,
    paddingTop: Platform.OS === "ios" ? 12 : 8,
    paddingBottom: 60,
  },
  headerSection: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 16,
    paddingTop: Platform.OS === "ios" ? 8 : 4,
  },
  backButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    justifyContent: "center",
    alignItems: "center",
  },
  title: {
    fontSize: 20,
    fontWeight: "700",
    textAlign: "center",
  },
  placeholder: {
    width: 40,
  },
  sectionCard: {
    borderRadius: 18,
    borderWidth: 1,
    padding: 16,
    marginBottom: 14,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 2,
  },
  formCard: {
    borderRadius: 18,
    borderWidth: 1,
    padding: 16,
    marginBottom: 14,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 2,
  },
  typeToggleContainer: {
    flexDirection: "row",
    borderRadius: 14,
    padding: 4,
    marginBottom: 16,
    borderWidth: 1,
  },
  typeButton: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 10,
    paddingHorizontal: 6,
    borderRadius: 10,
    minHeight: 44,
  },
  typeButtonActive: {
    borderWidth: 1,
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.08,
    shadowRadius: 2,
    elevation: 1,
  },
  expenseButton: {},
  incomeButton: {},
  transferButton: {},
  typeButtonText: {
    fontSize: 14,
    fontWeight: "600",
    marginLeft: 6,
  },
  typeButtonTextActive: {
    fontWeight: "700",
  },
  fixedContextCard: {
    borderRadius: 14,
    borderWidth: 1,
    padding: 12,
    marginBottom: 14,
  },
  fixedContextBadgeRow: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 4,
  },
  fixedContextBadgeText: {
    fontSize: 11,
    fontWeight: "700",
    marginLeft: 6,
    textTransform: "uppercase",
    letterSpacing: 0.5,
  },
  fixedContextName: {
    fontSize: 15,
    fontWeight: "800",
    marginBottom: 4,
  },
  fixedContextMetaRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  fixedContextMetaText: {
    fontSize: 12,
    fontWeight: "600",
  },
  amountHeroLabel: {
    fontSize: 13,
    fontWeight: "600",
    marginBottom: 8,
  },
  amountHeroContainer: {
    flexDirection: "row",
    alignItems: "center",
    borderRadius: 14,
    paddingHorizontal: 16,
    paddingVertical: 6,
    borderWidth: 1,
  },
  amountHeroCurrency: {
    fontSize: 28,
    fontWeight: "800",
    marginRight: 8,
  },
  amountHeroInput: {
    flex: 1,
    fontSize: 32,
    fontWeight: "800",
    paddingVertical: 8,
  },
  inputContainer: {
    flexDirection: "row",
    alignItems: "center",
    borderRadius: 12,
    marginBottom: 16,
    paddingHorizontal: 14,
    borderWidth: 1,
  },
  inputIcon: {
    marginRight: 10,
  },
  input: {
    flex: 1,
    paddingVertical: 14,
    fontSize: 15,
  },
  amountInput: {
    flex: 1,
    paddingVertical: 14,
    fontSize: 24,
    fontWeight: "bold",
    textAlign: "center",
  },
  currencySymbol: {
    fontSize: 20,
    fontWeight: "bold",
    marginLeft: 8,
  },
  accountHint: {
    flex: 1,
    marginLeft: 10,
    marginBottom: 0,
    lineHeight: 20,
    fontSize: 13,
  },
  noAccountCard: {
    flexDirection: "row",
    alignItems: "center",
    borderWidth: 1,
    borderRadius: 12,
    padding: 14,
    marginBottom: 8,
  },
  createAccountButton: {
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  createAccountButtonText: {
    color: "white",
    fontWeight: "bold",
    fontSize: 13,
  },
  accountLabel: {
    fontSize: 13,
    fontWeight: "600",
    marginBottom: 8,
  },
  transferSectionHeader: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 8,
  },
  transferHeaderIcon: {
    marginRight: 6,
  },
  transferDivider: {
    flexDirection: "row",
    alignItems: "center",
    marginVertical: 8,
  },
  transferDividerLine: {
    flex: 1,
    height: 1,
  },
  transferArrowBadge: {
    width: 26,
    height: 26,
    borderRadius: 13,
    borderWidth: 1,
    alignItems: "center",
    justifyContent: "center",
    marginHorizontal: 10,
  },
  accountsGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "space-between",
    marginBottom: 8,
  },
  accountCard: {
    width: "48%",
    borderRadius: 12,
    borderWidth: 1,
    padding: 12,
    marginBottom: 10,
  },
  accountCardCompact: {
    width: "48%",
    borderRadius: 12,
    borderWidth: 1,
    paddingVertical: 8,
    paddingHorizontal: 10,
    marginBottom: 8,
    minHeight: 52,
    justifyContent: "center",
  },
  accountCardTopRow: {
    flexDirection: "row",
    alignItems: "center",
  },
  accountCardIcon: {
    marginRight: 6,
  },
  accountNameCompact: {
    flex: 1,
    fontSize: 13,
    fontWeight: "700",
  },
  accountTypeCompact: {
    fontSize: 11,
    marginLeft: 22,
    marginTop: 2,
  },
  selectedAccountCard: {},
  accountName: {
    fontSize: 14,
    fontWeight: "700",
    marginTop: 4,
  },
  accountType: {
    fontSize: 12,
    marginTop: 2,
  },
  selectedAccountText: {
    color: "white",
  },
  sectionTitleRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 12,
  },
  sectionTitle: {
    fontSize: 15,
    fontWeight: "700",
    marginBottom: 12,
  },
  fieldRequirementText: {
    fontSize: 12,
    fontWeight: "600",
  },
  inlineErrorText: {
    fontSize: 12,
    fontWeight: "600",
    marginTop: 6,
  },
  categoriesGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "space-between",
    marginBottom: 20,
    paddingHorizontal: 5,
  },
  categoryCard: {
    width: (width - 100) / 2,
    borderRadius: 12,
    padding: 12,
    marginBottom: 10,
    borderWidth: 2,
    alignItems: "center",
    minHeight: 80,
    justifyContent: "center",
  },
  categoryIcon: {
    width: 32,
    height: 32,
    borderRadius: 16,
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 6,
  },
  categoryName: {
    fontSize: 11,
    fontWeight: "600",
    textAlign: "center",
    lineHeight: 14,
  },
  categorySelector: {
    flexDirection: "row",
    alignItems: "center",
    borderWidth: 1,
    borderRadius: 12,
    paddingHorizontal: 14,
    paddingVertical: 14,
  },
  categorySelectorText: {
    flex: 1,
    fontSize: 15,
    marginLeft: 10,
  },
  categoryModalOverlay: {
    flex: 1,
    justifyContent: "flex-end",
    backgroundColor: "rgba(0, 0, 0, 0.5)",
  },
  categoryModal: {
    maxHeight: "72%",
    borderTopLeftRadius: 22,
    borderTopRightRadius: 22,
    padding: 20,
  },
  selectedCategoryName: {
    fontWeight: "bold",
  },
  noteInput: {
    minHeight: 80,
    textAlignVertical: "top",
  },
  saveButton: {
    borderRadius: 14,
    paddingVertical: 16,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    marginTop: 6,
    marginBottom: 24,
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.15,
    shadowRadius: 6,
    elevation: 4,
  },
  saveButtonDisabled: {
    backgroundColor: "#B0BEC5",
    shadowOpacity: 0,
    elevation: 0,
  },
  saveButtonText: {
    color: "white",
    fontSize: 16,
    fontWeight: "700",
    marginLeft: 8,
  },
  dateSelector: {
    flexDirection: "row",
    alignItems: "center",
    borderRadius: 12,
    paddingHorizontal: 14,
    paddingVertical: 14,
    borderWidth: 1,
  },
  dateSelectorText: {
    flex: 1,
    fontSize: 15,
    marginLeft: 10,
  },
  dateModalOverlay: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "rgba(0, 0, 0, 0.5)",
    padding: 24,
  },
  dateModal: {
    width: "100%",
    maxWidth: 380,
    borderRadius: 18,
    padding: 22,
  },
  dateModalHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  dateModalTitle: {
    fontSize: 18,
    fontWeight: "bold",
  },
  dateModalValue: {
    fontSize: 28,
    fontWeight: "bold",
    textAlign: "center",
    marginVertical: 26,
  },
  dateAdjustRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  dateAdjustButton: {
    width: 44,
    height: 44,
    borderRadius: 22,
    alignItems: "center",
    justifyContent: "center",
  },
  todayButton: {
    borderWidth: 1,
    borderRadius: 10,
    paddingHorizontal: 22,
    paddingVertical: 12,
  },
  todayButtonText: {
    fontWeight: "bold",
  },
  dateDoneButton: {
    alignItems: "center",
    borderRadius: 10,
    paddingVertical: 14,
    marginTop: 24,
  },
  dateDoneButtonText: {
    color: "white",
    fontWeight: "bold",
    fontSize: 16,
  },
});

export default styles;
