import { Dimensions, StyleSheet } from "react-native";
import { LightTheme } from "../../theme/theme";

const { width } = Dimensions.get("window");

const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  gradient: {
    flex: 1,
  },
  scrollContainer: {
    flexGrow: 1,
    paddingHorizontal: 20,
    paddingVertical: 14,
  },
  headerSection: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 18,
    paddingTop: 10,
  },
  backButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: "rgba(255, 255, 255, 0.2)",
    justifyContent: "center",
    alignItems: "center",
  },
  title: {
    fontSize: 24,
    fontWeight: "bold",
    color: "white",
    textAlign: "center",
  },
  placeholder: {
    width: 40,
  },
  formCard: {
    backgroundColor: "white",
    borderRadius: 20,
    padding: 18,
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 10,
    },
    shadowOpacity: 0.25,
    shadowRadius: 20,
    elevation: 15,
  },
  typeToggleContainer: {
    flexDirection: "row",
    backgroundColor: "#F8F9FA",
    borderRadius: 12,
    padding: 4,
    marginBottom: 16,
  },
  typeButton: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderRadius: 8,
  },
  typeButtonActive: {
    backgroundColor: "white",
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  expenseButton: {
    backgroundColor: "#FF6B6B",
  },
  incomeButton: {
    backgroundColor: "#4ECDC4",
  },
  transferButton: {
    backgroundColor: LightTheme.colors.primary,
  },
  typeButtonText: {
    fontSize: 16,
    fontWeight: "600",
    marginLeft: 8,
    color: "#666",
  },
  typeButtonTextActive: {
    color: "white",
  },
  inputContainer: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#F8F9FA",
    borderRadius: 12,
    marginBottom: 20,
    paddingHorizontal: 15,
    borderWidth: 1,
    borderColor: "#E9ECEF",
  },
  inputIcon: {
    marginRight: 12,
  },
  input: {
    flex: 1,
    paddingVertical: 15,
    fontSize: 16,
    color: LightTheme.colors.text,
  },
  amountInput: {
    flex: 1,
    paddingVertical: 15,
    fontSize: 24,
    fontWeight: "bold",
    color: LightTheme.colors.text,
    textAlign: "center",
  },
  currencySymbol: {
    fontSize: 20,
    fontWeight: "bold",
    color: LightTheme.colors.primary,
    marginLeft: 8,
  },
  accountHint: {
    color: "#777",
    flex: 1,
    marginLeft: 10,
    marginBottom: 0,
    lineHeight: 20,
  },
  noAccountCard: {
    flexDirection: "row",
    alignItems: "center",
    borderWidth: 1,
    borderRadius: 12,
    padding: 14,
    marginBottom: 20,
  },
  createAccountButton: {
    backgroundColor: LightTheme.colors.primary,
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  createAccountButtonText: {
    color: "white",
    fontWeight: "bold",
  },
  accountLabel: {
    color: "#666",
    fontSize: 14,
    fontWeight: "600",
    marginBottom: 8,
  },
  accountsGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "space-between",
    marginBottom: 20,
  },
  accountCard: {
    width: "48%",
    backgroundColor: "#F8F9FA",
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#E9ECEF",
    padding: 12,
    marginBottom: 10,
  },
  selectedAccountCard: {
    backgroundColor: LightTheme.colors.primary,
    borderColor: LightTheme.colors.primary,
  },
  accountName: {
    color: LightTheme.colors.text,
    fontSize: 15,
    fontWeight: "bold",
    marginTop: 6,
  },
  accountType: {
    color: "#777",
    fontSize: 12,
    marginTop: 2,
  },
  selectedAccountText: {
    color: "white",
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: "bold",
    color: LightTheme.colors.text,
    marginBottom: 15,
  },
  categoriesGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "space-between",
    marginBottom: 20,
    paddingHorizontal: 5,
  },
  categoryCard: {
    width: (width - 100) / 2,
    backgroundColor: "#F8F9FA",
    borderRadius: 12,
    padding: 12,
    marginBottom: 10,
    borderWidth: 2,
    borderColor: "#E9ECEF",
    alignItems: "center",
    minHeight: 80,
    justifyContent: "center",
  },
  categoryIcon: {
    width: 32,
    height: 32,
    borderRadius: 16,
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 6,
  },
  categoryName: {
    fontSize: 11,
    fontWeight: "600",
    color: "#666",
    textAlign: "center",
    lineHeight: 14,
  },
  categorySelector: {
    flexDirection: "row",
    alignItems: "center",
    borderWidth: 1,
    borderRadius: 12,
    paddingHorizontal: 14,
    paddingVertical: 14,
    marginBottom: 16,
  },
  categorySelectorText: {
    flex: 1,
    fontSize: 16,
    marginLeft: 10,
  },
  categoryModalOverlay: {
    flex: 1,
    justifyContent: "flex-end",
    backgroundColor: "rgba(0, 0, 0, 0.5)",
  },
  categoryModal: {
    maxHeight: "72%",
    borderTopLeftRadius: 22,
    borderTopRightRadius: 22,
    padding: 20,
  },
  selectedCategoryName: {
    color: LightTheme.colors.primary,
    fontWeight: "bold",
  },
  noteInput: {
    minHeight: 80,
    textAlignVertical: "top",
  },
  saveButton: {
    backgroundColor: LightTheme.colors.primary,
    borderRadius: 12,
    paddingVertical: 16,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    marginTop: 10,
    shadowColor: LightTheme.colors.primary,
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 8,
  },
  saveButtonDisabled: {
    backgroundColor: "#B0BEC5",
    shadowOpacity: 0,
    elevation: 0,
  },
  saveButtonText: {
    color: "white",
    fontSize: 18,
    fontWeight: "bold",
    marginLeft: 8,
  },

  dateSelector: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#F8F9FA",
    borderRadius: 12,
    marginBottom: 20,
    paddingHorizontal: 15,
    paddingVertical: 15,
    borderWidth: 1,
    borderColor: "#E9ECEF",
  },
  dateSelectorText: {
    flex: 1,
    fontSize: 16,
    color: LightTheme.colors.text,
    marginLeft: 12,
  },
  dateModalOverlay: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "rgba(0, 0, 0, 0.5)",
    padding: 24,
  },
  dateModal: {
    width: "100%",
    maxWidth: 380,
    borderRadius: 18,
    padding: 22,
  },
  dateModalHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  dateModalTitle: {
    fontSize: 18,
    fontWeight: "bold",
  },
  dateModalValue: {
    fontSize: 28,
    fontWeight: "bold",
    textAlign: "center",
    marginVertical: 26,
  },
  dateAdjustRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  dateAdjustButton: {
    width: 44,
    height: 44,
    borderRadius: 22,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: LightTheme.colors.primary,
  },
  todayButton: {
    borderWidth: 1,
    borderColor: LightTheme.colors.primary,
    borderRadius: 10,
    paddingHorizontal: 22,
    paddingVertical: 12,
  },
  todayButtonText: {
    color: LightTheme.colors.primary,
    fontWeight: "bold",
  },
  dateDoneButton: {
    alignItems: "center",
    backgroundColor: LightTheme.colors.primary,
    borderRadius: 10,
    paddingVertical: 14,
    marginTop: 24,
  },
  dateDoneButtonText: {
    color: "white",
    fontWeight: "bold",
    fontSize: 16,
  },
});

export default styles;
